server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: ecommerce-backend-spring

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce-backend-spring
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


