server:
  error:
    include-message: always
    include-binding-errors: always

frontend:
  url: http://localhost:3000

spring:
  application:
    name: ecommerce-backend-spring

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_backend_spring
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host:
      smtp.gmail.com
    port:
      587
    username:
      uminodev@gmail.com
    password:
      "pfcc bqsp mipw kzrv"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jackson:
    property-naming-strategy: SNAKE_CASE


logging:
  file:
    name: logs.log